In [40]:
from tensorflow.keras.preprocessing.text import one_hot

In [41]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [42]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [43]:
##Vocab size
voc_size = 10000


In [44]:
# one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9873, 5479, 401, 8756],
 [9873, 5479, 401, 7056],
 [9873, 666, 401, 4521],
 [862, 273, 4842, 7651, 1024],
 [862, 273, 4842, 7651, 8305],
 [8644, 9873, 9813, 401, 7191],
 [3278, 8020, 3108, 7651]]

In [45]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils  import pad_sequences
from tensorflow.keras.models import Sequential





In [46]:
import numpy as np

In [47]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9873 5479  401 8756]
 [   0    0    0    0 9873 5479  401 7056]
 [   0    0    0    0 9873  666  401 4521]
 [   0    0    0  862  273 4842 7651 1024]
 [   0    0    0  862  273 4842 7651 8305]
 [   0    0    0 8644 9873 9813  401 7191]
 [   0    0    0    0 3278 8020 3108 7651]]


In [51]:
# Define the input and embedding dimensions
input_dim = 10000   # vocabulary size (adjust this to get close to 100,000 params)
output_dim = 10     # embedding output size
input_length = 8    # sequence length (None represents dynamic batch size)

# Create the Embedding layer
embedding_layer = Embedding(input_dim=input_dim, output_dim=output_dim, input_length=input_length)

# Build the model with a placeholder input
model =Sequential([
    embedding_layer
])

# Summary to check output shape and params
model.build(input_shape=(None, input_length))
model.summary()

c:\Users\Waleed\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 277ms/step


array([[[ 0.03558377, -0.02756717,  0.01315895, -0.04797148,
         -0.04174238,  0.01336414, -0.01369597, -0.03101031,
         -0.00924556, -0.03810606],
        [ 0.03558377, -0.02756717,  0.01315895, -0.04797148,
         -0.04174238,  0.01336414, -0.01369597, -0.03101031,
         -0.00924556, -0.03810606],
        [ 0.03558377, -0.02756717,  0.01315895, -0.04797148,
         -0.04174238,  0.01336414, -0.01369597, -0.03101031,
         -0.00924556, -0.03810606],
        [ 0.03558377, -0.02756717,  0.01315895, -0.04797148,
         -0.04174238,  0.01336414, -0.01369597, -0.03101031,
         -0.00924556, -0.03810606],
        [-0.00520172,  0.03106414,  0.00290025,  0.00298883,
         -0.02139909,  0.04511309,  0.00492476, -0.0026915 ,
         -0.02180662, -0.04299033],
        [-0.01367334,  0.03889406, -0.03176571,  0.04886724,
         -0.03157171, -0.04704446, -0.04870397, -0.02562823,
          0.02467437, -0.01166333],
        [-0.00901311, -0.04977436, -0.01223023, -0.0